services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=testdb
    ports:
      - '5005:5005'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: